# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-09 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20190309_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
