# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-09 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20190309_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='alloted_bider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allotted_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
